management:
  endpoints:
    web:
      exposure:
        include: '*'
        
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sample2?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: microservice
    password: microservice
  jpa:
   hibernate:
    naming:
     physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    ddl-auto: update