server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/praveenmeka6/profile-service-config-store
          search-paths:
          - 'service-config/*service'
